sample:
  app:
    title: "Sample Application"
  custom:
    conf: "Custom Config Value"

---
spring:
  config.activate.on-profile: default,sample2
sample:
  unicode:
    chars: "-"

---
spring:
  config.activate.on-profile: sample2
sample:
  custom:
    conf: "Custom Config Value for sample2"
